### ISSUE TITLE
How to unselect a element in a Treemap ???

### ISSUE THREAD

**Issue by dgillier** [asantibanez/livewire-charts#101]
I'm using a Tree Map.

When user is clicking an item, it is select, the color of the clicked element is changed, and a Livewire event is launched, great !

But is it possible to unselect after processing the event ?

Thanks!
Denis

**Comment by asantibanez** [comment]
Hi @dgillier .

Thanks for putting an issue. 

Funny I didn't know this happens. It's a native ApexCharts behavior.

https://apexcharts.com/javascript-chart-demos/treemap-charts/basic/

I wonder if this is possible? If you find a way, don't hesitate to share to see if we can add this functionality. 👍
