### ISSUE TITLE
wire:poll isn't working

### ISSUE THREAD

**Issue by erkinov-wtf** [asantibanez/livewire-charts#106]
hi there. i wanted to refresh my chart components automatically without full refresh of the page, so for that i used wire:poll method, but it. doesnt work. I check it send update methods, but there's no change in chart until again full refresh. So guys if anyone know how to re-render chart component on given time, please help))

**Comment by joalea** [comment]
Hi, have you tried adding `key="{{ $columnChartModel->reactiveKey() }}"` inside the livewire chart component as the documentation suggests?

Full example:
`<livewire:livewire-column-chart
    key="{{ $columnChartModel->reactiveKey() }}"
    :column-chart-model="$columnChartModel"
/>`

**Comment by asantibanez** [comment]
Hello @erkinov-wtf . 

Try adding the `key` as @joalea suggests. That should fix it. Remember that the outer component housing the chart component should be the one that has the `wire:poll` configured.

**Comment by erkinov-wtf** [comment]
yeah guys thanks a lot, it worked
