### ISSUE TITLE
Chart components cannot be used inside and @if in Laravel blade template

### ISSUE THREAD

**Issue by acacha** [asantibanez/livewire-charts#12]
Hola Andrés, 

Felicidades, maravilloso paquete. Estoy utilitzando en un proyecto actualmente. Gracias por tu tiempo!

I cannot use you livewire-components inside and if:

```php
@if($show)
<livewire:livewire-column-chart
                key="{{ $columnChartModel->reactiveKey() }}"
                :column-chart-model="$columnChartModel"
            />
@endif

Error:

```
Uncaught ReferenceError: columnChart is not defined

```

As said in alpinejs docs:

https://github.com/alpinejs/alpine#x-data

Using '''window.''' in line:

https://github.com/asantibanez/livewire-charts/blob/master/resources/views/livewire-column-chart.blade.php#L9

solves the problem.

I will make a PR soon.

Greetings,

Sergi Tur

**Comment by acacha** [comment]
@asantibanez  PR https://github.com/asantibanez/livewire-charts/pull/13 created

**Comment by asantibanez** [comment]
Thanks @acacha . Much appreciated!

Can you try the latest release? It should address this one. Thanks!
