### ISSUE TITLE
Adjust colors for dark-mode

### ISSUE THREAD

**Issue by LordSimal** [asantibanez/livewire-charts#120]
### Summary
It would be nice if the default generated charts also look nice in dark mode. Some of us use system wide dark mode.

### Proposal
Adjust text colors etc. to be readable and apropriate in dark mode.

### Additional Notes
E.g. (those are generated entries, so don't worry 😉)

![image](https://github.com/asantibanez/livewire-charts/assets/9105243/2afffb10-50f4-4daf-8f3b-23893d207341)

**Comment by LordSimal** [comment]
Currently I just added this to my CSS
```
@media (prefers-color-scheme: dark) {
    .apexcharts-text.apexcharts-yaxis-label,
    .apexcharts-text.apexcharts-xaxis-label,
    .apexcharts-legend-series .apexcharts-legend-text {
        color: theme('colors.gray.300') !important;
        fill: theme('colors.gray.300');
    }

    .apexcharts-tooltip.apexcharts-theme-light .apexcharts-tooltip-title,
    .apexcharts-tooltip-text {
        color: theme('colors.gray.700');
        fill: theme('colors.gray.300');
    }
}
```

**Comment by Rusbelito** [comment]
thanks , its work for me , but it don't change the color of title :c

> Currently I just added this to my CSS
> 
> ```
> @media (prefers-color-scheme: dark) {
>     .apexcharts-text.apexcharts-yaxis-label,
>     .apexcharts-text.apexcharts-xaxis-label,
>     .apexcharts-legend-series .apexcharts-legend-text {
>         color: theme('colors.gray.300') !important;
>         fill: theme('colors.gray.300');
>     }
> 
>     .apexcharts-tooltip.apexcharts-theme-light .apexcharts-tooltip-title,
>     .apexcharts-tooltip-text {
>         color: theme('colors.gray.700');
>         fill: theme('colors.gray.700');
>     }
> }
> ```

**Comment by emanuelnogueiras** [comment]
I use tailwind with darkmode selector, I fix my own by adding...
--
/* Dark mode */
.dark .apexcharts-text.apexcharts-yaxis-label,
.dark .apexcharts-text.apexcharts-xaxis-label,
.dark .apexcharts-legend-series .apexcharts-legend-text,
.dark .apexcharts-text.apexcharts-yaxis-title-text {
    color: theme('colors.gray.300') !important;
    fill: theme('colors.gray.300');
}

.dark .apexcharts-tooltip.apexcharts-theme-light .apexcharts-tooltip-title,
.dark .apexcharts-tooltip-text {
    color: theme('colors.gray.700') !important;
    fill: theme('colors.gray.700');
}

/* Light mode */
.apexcharts-text.apexcharts-yaxis-label,
.apexcharts-text.apexcharts-xaxis-label,
.apexcharts-legend-series .apexcharts-legend-text,
.apexcharts-text.apexcharts-yaxis-title-text {
    color: theme('colors.gray.700') !important;
    fill: theme('colors.gray.700');
}

.apexcharts-tooltip.apexcharts-theme-light .apexcharts-tooltip-title,
.apexcharts-tooltip-text {
    color: theme('colors.gray.700') !important;
    fill: theme('colors.gray.700');
}
