### ISSUE TITLE
Add support for laravel 11.x

### ISSUE THREAD

**Issue by bourk94** [asantibanez/livewire-charts#126]
Could you please add support for laravel 11.x ?

**Comment by ekandreas** [comment]
Waiting

**Comment by ootri** [comment]
There is a pull request with a compatible branch for composer: https://github.com/asantibanez/livewire-charts/pull/122#issuecomment-1966816743
The package by itself seems compatible and this branch only updates it's composer.json, this could work as a solution until @asantibanez merges it.

**Comment by faakher** [comment]
any update for laravel 11 @asantibanez

**Comment by colivinggit** [comment]
I'm also waiting for Laravel 11 upgrade.

**Comment by Kotzilla** [comment]
Im Waiting

**Comment by sharat-rhinofish** [comment]
Please add support for Laravel 11.x. Thank you for developing such a fantastic package for Livewire charts

**Comment by asantibanez** [comment]
Added support in v4.0.0 release
