### ISSUE TITLE
setJsonConfig([]) is broken - Datetime not working

### ISSUE THREAD

**Issue by johannesMEGABAD** [asantibanez/livewire-charts#134]
**Describe the bug**
When using the function **setJsonConfig([])** like it is describe it errors and says "**datetime is undefined**".

**To Reproduce**
Do the same as in the screenshot and then look at the Browser console

**Expected behavior**
I expect the X-Axis to be the date that I passed in as the value.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/0d8ae8b9-cea1-4faa-823b-f62d2ee08357)

**Comment by securit** [comment]
Having the same problem here with multiLineCharts

As another suggestion for much more efficient loading and memory usage, perhaps https://github.com/asantibanez/livewire-charts/blob/35324eace3c45112935eba7ccca3087fa52deb48/src/Models/LineChartModel.php#L117 the fromArray could add the ability provide the x:y data as an array rather than multiple series objects per https://apexcharts.com/javascript-chart-demos/area-charts/datetime-x-axis.

**Comment by securit** [comment]
Ummm I was able to make a "workaround" by passing datetime as a string into the type. 
```php
$speedMultiLineChartModel = LivewireCharts::multiLineChartModel()
            ->setTitle('Speed over Time')
            ->setAnimated($this->firstRun)
            ->setSmoothCurve()
            ->multiLine()
            ->setDataLabelsEnabled($this->withDataLabels)
            ->withLegend()
            ->withGrid()
            ->setJsonConfig([
                'chart.toolbar.show' => 'true',
                'chart.zoom.enabled' => 'true',
                'xaxis.type' => '\'datetime\'',
                'xaxis.min' => ($fromDate->timestamp*1000),
                'xaxis.tickAmount' => 6,
            ]);
 ```
 
 I was also able to use the same methodology of escaped single quotes to get synched charts working too...
 ie
 ```php
 ->setJsonConfig(array_merge(self::CHART_OPTIONS, [
                'xaxis.min' => ($fromDate->timestamp * 1000),
                'chart.id' => '\'speed\'',
                'chart.group' => '\'svt\''
            ]));
 ```

**Comment by johannesMEGABAD** [comment]
> Ummm I was able to make a "workaround" by passing datetime as a string into the type.
> 
> ```
> $speedMultiLineChartModel = LivewireCharts::multiLineChartModel()
>             ->setTitle('Speed over Time')
>             ->setAnimated($this->firstRun)
>             ->setSmoothCurve()
>             ->multiLine()
>             ->setDataLabelsEnabled($this->withDataLabels)
>             ->withLegend()
>             ->withGrid()
>             ->setJsonConfig([
>                 'chart.toolbar.show' => 'true',
>                 'chart.zoom.enabled' => 'true',
>                 'xaxis.type' => '\'datetime\'',
>                 'xaxis.min' => ($fromDate->timestamp*1000),
>                 'xaxis.tickAmount' => 6,
>             ]);
> ```
> 
> I was also able to use the same methodology of escaped single quotes to get synched charts working too... ie
> 
> ```
> ->setJsonConfig(array_merge(self::CHART_OPTIONS, [
>                'xaxis.min' => ($fromDate->timestamp * 1000),
>                'chart.id' => '\'speed\'',
>                'chart.group' => '\'svt\''
>            ]));
> ```

Hey :)
Thanks for the reply. Yeah probably you can get it to work with some little hacking anyway for my use case I then decided to use ChartJS and got what I needed ^^
