### ISSUE TITLE
Charts resizing when window resizes

### ISSUE THREAD

**Issue by linusx** [asantibanez/livewire-charts#19]
When I resize the window in anyway, the charts start resizing and will continue until I reload the page.

![ChartResizing](https://user-images.githubusercontent.com/110362/101121655-a5ffdf80-35be-11eb-87d5-5d6cd81375d6.gif)

**Comment by ao-jhelmich** [comment]
Could you provide the code that you use?

Have you set a height on the parent element?

**Comment by asachanfbd** [comment]
Chart sizes are dependent on their container size. Check if your containers size depends on window size.

**Comment by linusx** [comment]
That would make sense. Let me give that a try.

**Comment by linusx** [comment]
That did it. Thanks.
