### ISSUE TITLE
[Q] How to customise colours?

### ISSUE THREAD

**Issue by Chazza** [asantibanez/livewire-charts#27]
Hi @asantibanez,

Traditionally with APEXCharts we are able to pass it a JSON config with all the options, looking at what you've provided so far it doesn't seem like we are able to do that.

Could you provide some documentation on how to do this with your laravel library please?

Thanks.

**Comment by asantibanez** [comment]
Hi @Chazza . Thanks for checking out the package.

Just adding it to a new release. Stay tuned!
