### ISSUE TITLE
Undefined variable: columnChartModel

### ISSUE THREAD

**Issue by ThomasAKaestner** [asantibanez/livewire-charts#32]
Hey. I am trying to create a chart by the example and running into the following issue. _Undefined variable: columnChartModel_  . How is the variable $columnChartModel passed into the view? I dont get it? Its not defined? Shouldn't there be a variable definde like 
`public $columnChartModel` ?
I had an old livewire component which I want to extend with a chart. 
I am extending my Component _RegisteredUseres_ 's render function by $columnChartModel 
```
 public function render()
    {
        $columnChartModel =
            (new ColumnChartModel())
                ->setTitle('Expenses by Type')
                ->addColumn('Food', 100, '#f6ad55')
                ->addColumn('Shopping', 200, '#fc8181')
                ->addColumn('Travel', 300, '#90cdf4')
        ;

        return view('livewire.registered-users');
    }
```

Then I am trying to call it inside my livewire view _registered-users_ with the following 
```
        <livewire:livewire-column-chart
            :column-chart-model="$columnChartModel"
        />
```

The livewireChartsScripts are successfully loaded into the page and I am using following dependencies  

```
        "php": "^7.3",
        "asantibanez/livewire-charts": "^2.3",
        "doctrine/dbal": "^2.12",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.0",
        "laravel/jetstream": "^1.5",
        "laravel/sanctum": "^2.6",
        "laravel/tinker": "^2.0",
        "livewire/livewire": "^2.0"

```
Any idea what I am doing wrong here? 
Thanks

**Comment by Tuginho** [comment]
Try this way:
`    public function render()
    {
        return view('tenant.livewire.dashboard.customer.anamnese', [
            'anamneseLogs' => $this->user->anamneseLogs,
            'columnChartModel' =>
                (new ColumnChartModel())
                    ->setTitle('Expenses by Type')
                    ->addColumn('Food', 100, '#f6ad55')
                    ->addColumn('Shopping', 200, '#fc8181')
                    ->addColumn('Travel', 300, '#90cdf4')
        ]);
    }`

**Comment by ThomasAKaestner** [comment]
@Tuginho Thanks a lot it worked!
