### ISSUE TITLE
[Question] Is there a way to change the formatting on a number (commas and dollar signs)?

### ISSUE THREAD

**Issue by shylor** [asantibanez/livewire-charts#34]
Is there a way to change the formatting on a number (commas and dollar signs)?

I think there is a way to do this in Apex, but not sure if there is a way to pass this through from livewire charts.

**Comment by vigstudio** [comment]
me too

**Comment by rudysetiawan** [comment]
hi @mafalda2007 or anyone , where do I put the number_format for a columnChartModel ? thank you in advance

below is my code:

` $history = TopUpHistory::whereIn('source_type',$this->types)->get();
        $columnChart = $history->groupBy('source_type')
            ->reduce(function ($columnChart, $data) {
                $type = $data->first()->source_type;
                $value = number_format($data->sum('amount'),2);
                //$value = $data->sum('amount');
                return $columnChart->addColumn($type, $value, $this->colors[$type]);
                //return $columnChart->addColumn($type, ['formatted' => 'IDR ' . number_format($value,2,',','')], $this->colors[$type]);
            }, LivewireCharts::columnChartModel()
                ->setTitle('Top Up Value')
                ->setAnimated($this->firstRun)
                ->withOnColumnClickEventName('onColumnClick')
                ->setLegendVisibility(true)
                ->setDataLabelsEnabled($this->showDataLabels)
                //->setOpacity(0.25)
                ->setColors(['#b01a1b', '#d41b2c', '#ec3c3b', '#f66665'])
                ->setColumnWidth(90)
                ->setYAxisVisible(1)
                ->withGrid()
            );`

**Comment by asantibanez** [comment]
Hello @shylor 

You can do this now using `extras.tooltip` in the latest version of the library.

**Comment by kraglr** [comment]
Hi, can you give an example how to implement the extra.tooltip. thank you!

**Comment by fcmpeixoto** [comment]
Em addColumn($title, $value, $color, $extras = []), no quarto paremetro voce coloca 
 ['tooltip' => 'IDR ' . number_format($value,2,',','')]


$columnChart = $history->groupBy('source_type')

        ->reduce(function ($columnChart, $data) {

            $type = $data->first()->source_type;

            $value = number_format($data->sum('amount'),2);

            //$value = $data->sum('amount');

            return $columnChart->addColumn($type, $value, $this->colors[$type], ['tooltip' => 'IDR ' . number_format($value,2,',','')]);

            //return $columnChart->addColumn($type, ['formatted' => 'IDR ' . number_format($value,2,',','')], $this->colors[$type]);

        }, LivewireCharts::columnChartModel()

            ->setTitle('Top Up Value')

            ->setAnimated($this->firstRun)

            ->withOnColumnClickEventName('onColumnClick')

            ->setLegendVisibility(true)

            ->setDataLabelsEnabled($this->showDataLabels)

            //->setOpacity(0.25)

            ->setColors(['#b01a1b', '#d41b2c', '#ec3c3b', '#f66665'])

            ->setColumnWidth(90)

            ->setYAxisVisible(1)

            ->withGrid()

        );

**Comment by Acentrix-Jordan** [comment]
> .

Can't seem to find this reference in the documentation. Can anybody provide a link?
