### ISSUE TITLE
Time series line chart

### ISSUE THREAD

**Issue by thomasjohnkane** [asantibanez/livewire-charts#4]
@asantibanez - this package is awesome. Can't believe how easy it is to get started.

Would you mind showing an example of a time-series line chart? Similar to this perhaps: https://apexcharts.com/javascript-chart-demos/line-charts/basic/

Thanks,

**Comment by asantibanez** [comment]
Hi @thomasjohnkane! 

Thank you!

There is a demo repo of `livewire-charts` here. https://github.com/asantibanez/livewire-charts-demo

Check it out!

**Comment by thomasjohnkane** [comment]
Thanks @asantibanez - I sorted it out. Replaced the "reduce" example. I'll hope to add some other examples to that demo in the future.
