### ISSUE TITLE
Not working with AlpineJS V3

### ISSUE THREAD

**Issue by Tuginho** [asantibanez/livewire-charts#56]
After upgrading alpinejs, charts not working.
Any tips to upgrade livewire-charts?

![image](https://user-images.githubusercontent.com/17098483/141643540-c653afa7-fcb8-4c71-90d9-ea93f9396f92.png)

**Comment by marask** [comment]
Same issue here

**Comment by marask** [comment]
Happened to me once, you probably forgot to include the @livewireChartsScripts directive ;)

**Comment by hsmfawaz** [comment]
I had the same issue its because I was using 2 versions of alpine at the same time

**Comment by asantibanez** [comment]
Hi @Tuginho 

Library works with Alpine v2 and v3. Just tested it out with v3. No issues at all. 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/5126648/216142501-0a5b7fda-e9f9-4aee-8d18-f1dfb5cf6044.png">
