### ISSUE TITLE
Titles aren't set on multiline charts

### ISSUE THREAD

**Issue by mokhosh** [asantibanez/livewire-charts#6]
When I use `multiline` charts, the second argument doesn't have any effect. My labels are a sequence of 1 to items count regardless.

**Comment by asantibanez** [comment]
Hi @mokhosh 

This has been fixed in v1.4.0. 

I've also added support for custom categories/labels. You can use `setXAxisCategories` for this.

Check it out!

Thanks for the feedback!

**Comment by mokhosh** [comment]
Will do thanks
