### ISSUE TITLE
Livewire component's [tenants.dash-board.employee-chart] public property [columnChartModel] must be of type: [numeric, string, array, null, or boolean]. Only protected or private properties can be set as other types because JavaScript doesn't need to access them.

### ISSUE THREAD

**Issue by timore333** [asantibanez/livewire-charts#61]
Livewire component's [tenants.dash-board.employee-chart] public property [columnChartModel] must be of type: [numeric, string, array, null, or boolean]. Only protected or private properties can be set as other types because JavaScript doesn't need to access them.

**Comment by xitude** [comment]
How did you solve this? Please try to not close issues without some form of comment explaining what you did to move past it. It helps people solve similar issues.

**Comment by jasonmm** [comment]
[This comment on an earlier issue](https://github.com/asantibanez/livewire-charts/issues/37#issuecomment-859958123) is the solution I used.
