### ISSUE TITLE
Multi Column Charts

### ISSUE THREAD

**Issue by craigpotter** [asantibanez/livewire-charts#7]
Hey, 

Great package. 
Have you thought about adding support for multi-column column charts ? (Too many columns!) 

https://apexcharts.com/javascript-chart-demos/column-charts/basic/ 

I did look at the source but couldn't think of a way to do this without a massive breaking change or creating a new chart type. 

Didn't want to spend time on this and submit a PR if it isn't something you would like to support going forward.

**Comment by asantibanez** [comment]
Hi @craigpotter 

Multi-column charts are supported in v1.4.0. Check them out! 💪

Thanks for the suggestion!
