### ISSUE TITLE
Single line chart change color.

### ISSUE THREAD

**Issue by essodinho45** [asantibanez/livewire-charts#90]
I'm creating a single line chart and I couldn't find a way to change line stroke color in LineChartModel.
can you help me with that?

**Comment by jonfackrell** [comment]
@essodinho45 did you ever figure out how to change the color on a single line chart? I'm having the same issue.

**Comment by robbiechicago** [comment]
This appears to still be an issue. The docs suggest $chart->setColors(['##FF8C00']) should work but it doesn't for me. 

Annoyingly the example line chart is just using the default colour. @asantibanez is there any chance the example repo could be updated with a working change of colour on the line chart?

**Comment by essodinho45** [comment]
> @essodinho45 did you ever figure out how to change the color on a single line chart? I'm having the same issue.

not yet

**Comment by m1ge0** [comment]
Run into the same problem. My solution was to change the color of the apexchrt-line class. 

`.apexcharts-line { stroke: green !important;  }`

Hope it helps ✌🏼

**Comment by essodinho45** [comment]
> Run into the same problem. My solution was to change the color of the apexchrt-line class.
> 
> `.apexcharts-line { stroke: green !important; }`
> 
> Hope it helps ✌🏼

I'm gonna try it, although it should be an option in the component itself and should not be added manually, thank you very much for the solution.

**Comment by essodinho45** [comment]
> .apexcharts-line { stroke: green !important; }

as @m1ge0 mentioned, it can be solved this way, thanks dude!
