### ISSUE TITLE
Package Abandoned like the rest?

### ISSUE THREAD

**Issue by lrljoe** [asantibanez/livewire-charts#98]
I think @asantibanez may have abandoned his projects. Anyone got any recommendations for an alternative?

**Comment by lrljoe** [comment]
I've created a fork for LW3 support, and will be introducing a few of the missing charts as/when I need them, if anyone has any PRs outstanding, or has already made improvements, then please feel free to open a PR
[Here](https://github.com/LowerRockLabs/livewire-charts)

**Comment by mnluribef** [comment]
> I think @asantibanez may have abandoned his projects. Anyone got any recommendations for an alternative?

Hi, i found this post `https://www.georgebuckingham.com/laravel-livewire-chart-js-realtime/`

Tried it and it renders the graph initially, but when trying to update data gives this error: Attempt to read property "id" on null, file wan-speed-tests.blade.php, line 5 <div wire:ignore wire:key={{ $chart->id }}>

Good thing is that the graph loads fast.

**Comment by asantibanez** [comment]
Hi @lrljoe .

Thanks tagging along. Updates have been coming slow but still pushing some. LW3 support is up too. Feel free to contribute here or in your fork. All help and feedback are welcomed.
