### ISSUE TITLE
Livewire 3 suppport

### ISSUE THREAD

**Issue by gregorysouzasilva** [asantibanez/livewire-charts#99]
Hello,
any plans to support livewire 3? or has anyone created fork with the updated version?

Tks

**Comment by lrljoe** [comment]
My fork of this works with LW3, although I have not introduced any of the performance improvements yet

**Comment by gregorysouzasilva** [comment]
thanks @lrljoe

**Comment by lrljoe** [comment]
Plan is to:
Update all dependencies properly
Introduce the other charts
Bring codebase up to scratch for typehinting etc
Introduce the missing config options
Introduce any LW3 features that will prove useful

But I don't have a timescale just yet as I maintain other packages that need more work to get LW3 ready.

**Comment by asantibanez** [comment]
Hello @gregorysouzasilva . Thanks for asking. It's coming. I'm updating the repo to support v3.

**Comment by lrljoe** [comment]
@asantibanez - is v3 supported now, or is it still in progress?

**Comment by clarg18** [comment]
Docs say it requires Livewire v3

**Comment by asantibanez** [comment]
L3 support is ready.
